### ISSUE TITLE
Docker daily builds and latest tag

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#28]
Because of some broken pipeline runs, It would be better to assign docker latest tag to latest released github version, not  to the master branch. In this case it is also crucial to stop daily rebuilding of released stable docker container.
@bgruening Which entity triggers the daily builds of the tags? How can I stop the daily automatic rebuilds :-D?

**Comment by bgruening** [comment]
The base image is pinned: https://github.com/BackofenLab/docker-galaxy-graphclust/blob/master/Dockerfile#L3
I removed the automatic link to the galaxy-stable image, which gets rebuild every 24h, to get latest updates and bugfixes - imho we should keep this.

The interesting question is what broke and why? ;)

**Comment by mmiladi** [comment]
Where is this automatic link to the galaxy-stable image :-D?

The main reason is there are many entities (conda builds, toolshed wrappers) not in control of this repository. So I would prefer to have the released latest versions tested ;-)

**Comment by mmiladi** [comment]
@bgruening The workflow currently fails to open: Error is `Following tools missing: [u'toolshed.g2.bx.psu.edu/repos/bgruening/infernal/infernal_cmbuild/1.1.0.2']`

**Comment by bgruening** [comment]
We can pin TS revisions to prevent this. But in general you can simply tag git releases and then you get a Docker pinned image. This can also point to latest.

**Comment by mmiladi** [comment]
Good idea, we tag latest release with 'latest' and master branch with 'development' 

>I removed the automatic link to the galaxy-stable image,

This I don't get. The dockerfile is not changed, where was the automatic link?

**Comment by bgruening** [comment]
Let's discuss this tomorrow and I will show you how to do this.

**Comment by mmiladi** [comment]
:+1:
