### ISSUE TITLE
Galaxy tour

### ISSUE THREAD

**Issue by bgruening** [BackofenLab/GraphClust-2#3]
* [x] a simple Galaxy UI tool
* [ ] A Galaxy tour that guides through an entire clustering step.
* [ ] Link both from the front page

**Comment by bgruening** [comment]
@eteriSokhoyan can you test please all tours again, so that we can close this issue?
The third item will be fixed in the welcome page update. We are getting close!

**Comment by eteriSokhoyan** [comment]
@bgruening i checked the tours again, i think they are fine (unless you found something specific that needs to be fixed). Only sometimes the positions of pop-up windows change, but i guess that's because of the screen resolution or something like that.

**Comment by mmiladi** [comment]
@eteriSokhoyan Please check the refined galaxy_tutorial (former galaxy_wf) and update the other two tours accordingly. You can diff galaxy_tutorial with your local galaxy_wf to see the changes.

**Comment by mmiladi** [comment]
@eteriSokhoyan For step_by_step tour one missing step for each tool is to open (or guide user to open)  the corresponding wrapper. Also please consider elaborate more details for each wrapper.

**Comment by mmiladi** [comment]
@eteriSokhoyan The visualization works and is really nice! For the upcoming week please consider update the tutorial tour with mentioning visual output and also improving the step-step tour.

**Comment by mmiladi** [comment]
@eteriSokhoyan we should go together through the tours once again and improve them. They are yet good enough for submission.
