### ISSUE TITLE
Locarna Free-endgaps option for collect results

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#34]
Hi @eteriSokhoyan , could you please think of adding free-endgaps option to locarna options of the collect results? You can get the template from original locarna package. or even better integrate locarna wrapper inside/after collect-results

**Comment by mmiladi** [comment]
@eteriSokhoyan Could you please check this

**Comment by eteriSokhoyan** [comment]
Hi @mmiladi , i don't really understand what you mean...can you please explain again what exactly you want.

**Comment by mmiladi** [comment]
There is an option in locarana named "free-endgaps". It is already integrated in original locarna wrapper, we need to add that to graphclust locarna wrappers as well.
