### ISSUE TITLE
Improve wrapper namings

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#35]
- premlocarna -> ?
- locarna_best_subtree -> locarna_graphclust
- Cmfinder_v0 -> cmfinder
- Report_results -> cluster_collection_report

**Comment by mmiladi** [comment]
@eteriSokhoyan could you please help to generate an snapshot like this but with renamed wrapper names? We need it for the manuscript so you can just change the names in your local instance, later you can make a PR.

**Comment by mmiladi** [comment]
![snapshot_minimal](https://cloud.githubusercontent.com/assets/6370737/23341898/a033e6e2-fc50-11e6-8550-88e734bb6eab.png)

**Comment by eteriSokhoyan** [comment]
Yes sure, i will do and send you tomorrow early in the morning. 
Only i'm not sure how to name the the premlocarna tool. There tree and tree_matrix files are generated.

**Comment by mmiladi** [comment]
Thanks! If you manage print the page and make a pdf file would be great, then we have a vector graphic isntead of png.
For premlocarna, whats are the name of tools called from locarna package? Was that sth like locarna_reliabiLity profile..?

**Comment by eteriSokhoyan** [comment]
Actually in that script we call pgma program. Should i call it like pgma_graphclust ?
