### ISSUE TITLE
Master 'dev/ version needs more testing

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#36]
With the lastest version of the docker with tag 'dev' in cases the workflow fails on cmsearch step. @eteriSokhoyan I think you were right something is getting incompatible. Please keep this issue in highest priority to check and resolve.

**Comment by eteriSokhoyan** [comment]
@mmiladi is now docker running with 'dev' tag? it doesn't fail for me. Also yesterday i was working with dev tag and cmsearch didn't fail

**Comment by mmiladi** [comment]
I revert back to latest tag, since the disk usage was also very high with dev tag, let me test same things for both tags then I'll update and we can see. For the manuscript it's not a big issue, I just run plotter and R-scape on my computer

**Comment by eteriSokhoyan** [comment]
ok, but anyway that's weird, cz nothing changed for cmsearch input or output. Do you know with what kind of error it was failing?

**Comment by mmiladi** [comment]
The cmfinder stockholm file was empty then cmsearch failed. What was the error you faced yesterday? As I said the disk was almost full. I try to reproduce the error.

**Comment by eteriSokhoyan** [comment]
My error was connected with workflows. If you manage to reproduce the error send me the log, i will try to fix it.

**Comment by mmiladi** [comment]
It's not related to dev/master version, with stable version also it can happen.
From top to down, cmbuild fails because cmfinder stk file is empty. cmbuild logs:
```
Alignment input parse error:
   #=GC line missing annotation?
   while reading Stockholm file /export/galaxy-central/database/files/003/dataset_3511.dat
   at or near line 3
```
CMfinder log:
```
Use of uninitialized value $aln_cons_struct in scalar chomp at /export/tool_deps/_cache/f1fa07f6/bin/alifold.pl line 46.
Use of uninitialized value $aln_cons_struct in pattern match (m//) at /export/tool_deps/_cache/f1fa07f6/bin/alifold.pl line 47.
Use of uninitialized value in print at /export/tool_deps/_cache/f1fa07f6/bin/alifold.pl line 50.
mv: cannot stat ‘alirna.ps’: No such file or directory
mv: cannot stat ‘aln.ps’: No such file or directory

FATAL: Stockholm format parse error: line 3 of file model.tree.stk while reading alignment 
```

**Comment by mmiladi** [comment]
Probably One step before: Tool: locarna_best_subtree:
```
end of stdout: No subtree/cluster with model criteria found in tree! No model will be build. Exit...

stderr:
Unknown option: c
Unknown option: l
Unknown option: w
Warning: maligs.loc_new/1 exists already.
Warning: maligs.loc_new/13 exists already.
Warning: maligs.loc_new/22 exists already.
Warning: maligs.loc_new/29 exists already.
```

**Comment by eteriSokhoyan** [comment]
yeah i saw it. 
I'm checking it now.

**Comment by mmiladi** [comment]
So in fact it is ok to have these cases, and also the pipeline successully skips failing until cmfinder step, if you could handle the case in cmfinder or cmbuild such that cmbuild does not fail, it would be fine

**Comment by eteriSokhoyan** [comment]
So it's ok when there is no model in some cases?

**Comment by mmiladi** [comment]
This is current cmfinder stk output with the message above
```
# STOCKHOLM 1.0

#=GC SS_cons          
//
```

**Comment by eteriSokhoyan** [comment]
i know, i checked the could instance with admin username and saw the output and problems

**Comment by mmiladi** [comment]
Yes it can happen that no part of cnadidate cluster is useful i don't know exactly how but if you could handle the cases we don't need to investigate at least for now why no model found

**Comment by mmiladi** [comment]
Aha nice!

**Comment by mmiladi** [comment]
what happens if you replace empty stk file of cmfinder with empty/no-output? Somehow to skip that output from stk data-collection

**Comment by mmiladi** [comment]
If that be possible then cmbuild would not be invoked at all for that empty model

**Comment by eteriSokhoyan** [comment]
ok, i will try to fix it now. I downloaded the data u were working on, and now i'm trying to reproduce the same on my local instance. Because with the datasets i tested before i never had a case like this. 

yes i will try to somehow ignore the empty outputs.

**Comment by mmiladi** [comment]
Thanks much! Can i restart the cloud instance?

**Comment by eteriSokhoyan** [comment]
yeah,  you can
