### ISSUE TITLE
R-scape output

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#39]
Hi Eteri,
Do you include all R-scape output (all pdf and svg figures, text output) to the Results.zip directory?

**Comment by eteriSokhoyan** [comment]
@mmiladi yup, everything is included there.

**Comment by mmiladi** [comment]
Nice!

**Comment by mmiladi** [comment]
Maybe later we expose one more output in history. Yet I don't know if needed.
