### ISSUE TITLE
Change welcome page and add more help text.

### ISSUE THREAD

**Issue by bgruening** [BackofenLab/GraphClust-2#4]

**Comment by mmiladi** [comment]
@bgruening By 'welcome page' do you mean the readme file or something different?

**Comment by bgruening** [comment]
The welcome page in the Docker container, it should be more related to GraphClust, with a link to original Paper, the tour should open etc ...

**Comment by bgruening** [comment]
How you add a customized welcome page to the container: https://github.com/bgruening/docker-galaxyp/blob/master/Dockerfile#L27

**Comment by mmiladi** [comment]
I think we can close this issue.

**Comment by bgruening** [comment]
Do we want to highlight the tour more.

**Comment by mmiladi** [comment]
I have removed other buttons from the welcome page. Do you think we need more?
https://github.com/BackofenLab/docker-galaxy-graphclust/pull/19

**Comment by bgruening** [comment]
Oh haven't checked ... tahnks

**Comment by mmiladi** [comment]
Thank you. The other issue https://github.com/BackofenLab/docker-galaxy-graphclust/issues/5 about unavailability of workflows for newly registered users might be a problem yet. Is it because import_workflows.py have not been triggered?  How this is handled in Fr-Galaxy instance?

**Comment by bgruening** [comment]
You can share it with everyone via the UI, I haven't yet found a API to do this programmatically :(
