### ISSUE TITLE
With recent updates Workflows are not automatically added during docker build

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#49]

**Comment by bgruening** [comment]
Mh ... is this because the workflow crashes during import, aka the tools are not installed/updated?

**Comment by mmiladi** [comment]
Actually idk. Where should we track it here : https://hub.docker.com/r/backofenlab/docker-galaxy-graphclust/builds/bkkzxd5w2yqjberzxxvk4qn/
Or while loading the container?

**Comment by bgruening** [comment]
idk?

**Comment by bgruening** [comment]
Ah, ok got it.

**Comment by mmiladi** [comment]
:haircut_man: :D

**Comment by mmiladi** [comment]
Resolved. Thank you @bgruening
