### ISSUE TITLE
Testing the tools and workflows

### ISSUE THREAD

**Issue by bgruening** [BackofenLab/GraphClust-2#5]
Please add all things that you encounter to this issue.

**Comment by mmiladi** [comment]
Issue: 'No workflows is shared with a created user.'
After pulling the container on my laptop and registering a user. Under workflows message is: No workflows have been shared with you.

**Comment by bgruening** [comment]
Can you go to the top menu and click on shared-data -> workflows.

**Comment by mmiladi** [comment]
Empty as well

**Comment by mmiladi** [comment]
Observation: Workflows are shared with admin user

**Comment by mmiladi** [comment]
@eteriSokhoyan Using the dataset provided by the tour, evaluation reports are set to 'NA'. Could you please check the evaluations is performed in the latest version of the Docker Instance?

**Comment by eteriSokhoyan** [comment]
@mmiladi i sent you an email with the explanation of this issue.
