### ISSUE TITLE
Readme file needs to be updated

### ISSUE THREAD

**Issue by bgruening** [BackofenLab/GraphClust-2#6]
* [ ] more installation guidance 
* [ ] aim, motivation, ref to the graphclust paper

**Comment by mmiladi** [comment]
@bgruening I am yet not sure how to seperate workflow info content between bioinf website and the github page. What's your opinion?

**Comment by bgruening** [comment]
Actually I'm not so convinced by the bioinf website, this makes everything just complicated and  separated in a strange way.

**Comment by mmiladi** [comment]
Well i am searching for a place to put the three forms of availability (docker, tools&workfliws, cloud-instance with links and IP there). Plus corresponding email addresses. They don't perfectly fit to github page.  But you are also right.
How about updating the original GraphClust website and there refer to the github page?

**Comment by bgruening** [comment]
I guess this plus keeping all information's on github is the cleanest way to go.

**Comment by mmiladi** [comment]
Readme is in an acceptable state, I'll gradually contribute more if needed
