### ISSUE TITLE
GraphClust-2 on RNA-seq data?

### ISSUE THREAD

**Issue by mavino** [BackofenLab/GraphClust-2#71]
Mine is a question and not an issue, I am very new to this area.
I got a rich deepgen fastq data set (coming from rna-seq data) of an organism we know the reference genome but nothing about non coding RNA.
I easily got a bam file out of it after quality control and alignment...
is there any way I could use graph-clust-2 to detect and classify non coding RNA in the whole genome starting from the bam file?
Will it make sense for my purpose to use your software?
Thank you very much!

**Comment by mmiladi** [comment]
Hi @mavino ,

GraphClust2 can be used to classify ncRNAs. The baseline input would be fasta files, alternatively, you may start from region information (e.g., a BED file or GTF file) using auxiliary tools available in Galaxy.
The tool is not designed for the purpose of separating ncRNAs from protein-coding RNAs.
Best,
-M

**Comment by mavino** [comment]
Thank you so much for the prompt and helpful answer!!
